  [build]
  builder = "nixpacks"

  [deploy]
  startCommand = "python3 -c \"import os, sys; sys.path.append('backend_fastapi'); exec('import uvicorn; from app.main import app; uvicorn.run(app, host=\\\"0.0.0.0\\\", port=int(os.getenv(\\\"PORT\\\", 8000)))')\""
